nnoremap <silent>11 :tabnext 1<CR>
nnoremap <silent>22 :tabnext 2<CR>
nnoremap <silent>33 :tabnext 3<CR>
nnoremap <silent>44 :tabnext 4<CR>
nnoremap <silent>55 :tabnext 5<CR>
nnoremap <silent>66 :tabnext 6<CR>
nnoremap <silent>77 :tabnext 7<CR>
nnoremap <silent>88 :tabnext 8<CR>
nnoremap <silent>99 :tabnext 9<CR>
nnoremap <silent>00 :tabnext 10<CR>
